### ISSUE TITLE
Requirements / outcome visualisation document for the MIT AI Demo project

### ISSUE THREAD

**Issue by faizmagic** [beckn/beckn-action-bot#11]
## Description

Prepare a requirements documents, that outlines the following

## Goals

- [ ] Define the Functional Requirements for building an AI agent for the MIT Demo
- [ ] Define the Outcome visualisation, defining personas and how the end user will be interacting / using the product 
- [ ] Define the success criteria for the MIT Demo

## Expected Outcome

An end-to-end demo of a Whatsapp based conversation where the user is able to discover and book stay, event tickets at Yellowstone national park and also be able to discover and book EV chargers during his drive there.

## Acceptance Criteria

- [ ] Functional Requirements are clearly defined
- [ ] Outcome visualisation should be defined
- [ ] Success criteria to be clearly defined

## Implementation Details

1. For whatsapp api, we will be using wati https://www.wati.io/
2. Bot will be build using nodejs
3. Required catalogs will be implemented using strapi bpp

## Mockups / Wireframes

Mockups / wireframes if required will be provided

---
[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

AI Demo

### Project Name

This project is for the MIT Demo, planned for april 9th

### Tech Skills Needed:

AI, Nodejs

**Comment by faizmagic** [comment]
Requirements are currently captured in the document. https://docs.google.com/document/d/1iW433h0A5gfw8dfchSsAic_qd5DEvOmyqDmmUubvbh8/edit#heading=h.qfaskyl5y0hz. its better if we move the doc to confluence under 

https://fide-official.atlassian.net/wiki/spaces/EC/pages/290029569/Beckn+-+AI

**Comment by pri233** [comment]
@ravi-prakash-v  Please validate this if the requirement is accurately captured
