### ISSUE TITLE
Create catalog in Excel based on inputs

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#18]
## Description

Create data in Excel for the five categories that will be used during the demo.
Hotel booking
Retail
DHP
EV
Ticket booking

https://docs.google.com/spreadsheets/d/1X6RPNJH2eQrpjvHtZte9Jw6Zy0fIj7MNOcdlpr5iphE/edit#gid=198792933

## Goals

- [ ] Research the catalog items and create a catalog that looks genuine based on the inputs provided [here](https://docs.google.com/document/d/1mqN5MD9l5JlsetIEe1B8WTlpdxIk4g9w3Y0q9bcU1A4/edit?pli=1#heading=h.bzr101xwyivz)

## Expected Outcome

Geniune-looking catalog for all 5 use cases.

## Acceptance Criteria

- [ ] 5 items for each use case

**Comment by zoyaashik** [comment]
Reassigning the ticket to @vishi24 as he worked up on creating data in excel
