### ISSUE TITLE
Upload catalogs to respective Strapi instance

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#19]
## Description

The catalogs are created in excel https://docs.google.com/document/d/1mqN5MD9l5JlsetIEe1B8WTlpdxIk4g9w3Y0q9bcU1A4/edit?pli=1#heading=h.bzr101xwyivz , now the catalogs are required to be uploaded to the respective Strapi instance.
The details for the Strapi instance are in Infra sheet along with the login creds.

https://mit-bpp-hotel.becknprotocol.io/admin - hotel booking
https://mit-bpp-tourism.becknprotocol.io/admin - ticket
https://mit-bpp-healthcare.becknprotocol.io/admin - DHP
https://mit-bpp-retail.becknprotocol.io/admin - Retail
https://mit-bpp-energy.becknprotocol.io/admin - EV

## Goals

- [ ] All the catalogs are populated properly into their respective Strapi instances.

## Expected Outcome

5 bpp instances with complete catalogs.

## Acceptance Criteria

- [ ] Catalogs must be completely populated,

**Comment by vishi24** [comment]
It is spanned over 3 days bcz it has dependency on Strapi being able to accommodate hotel and ticket usecase.

**Comment by zoyaashik** [comment]
The catalog has been uploaded for below domains
1.retail
2.EV
3.DHP
4.Hotel

**Comment by zoyaashik** [comment]
The catalogs for DHP are only partially uploaded. Hence rectified errors and uploaded missing data.

**Comment by zoyaashik** [comment]
Also, Sample catalog for ticket booking is uploaded. Need to upload remaining 3 catalogues
