### ISSUE TITLE
Catalog validation

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#20]
## Description

The catalogs are created and populated in the Strapi BPP instances and need validation that they are in line with the demo requirement.

https://mit-bpp-hotel.becknprotocol.io/admin
https://mit-bpp-tourism.becknprotocol.io/admin
https://mit-bpp-healthcare.becknprotocol.io/admin
https://mit-bpp-retail.becknprotocol.io/admin
https://mit-bpp-energy.becknprotocol.io/admin

## Goals

- [ ] Catalog validation for all 5 instances.

## Expected Outcome

The catalogs are verified and do not need any further changes.

## Acceptance Criteria

- [ ] Catalogs validated as per the Demo requirements.

**Comment by pri233** [comment]
@mayurvir  Please let us know once you validate 1 catalog per domain
