### ISSUE TITLE
Example JSON for hotel use case

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#21]
## Description

Currently, there are no sandbox collection / JSON examples for the hotel booking use case.
Study hotel booking websites and based on that create the JSON examples for hotel booking use case.

Please push the examples to https://github.com/beckn/beckn-sandbox/tree/main/src  under respective folder.

## Goals

- [x] Json examples for hotel booking use case

## Expected Outcome

JSON examples for the hotel booking use case.

## Acceptance Criteria

- [x] JSON examples should contain search, select, init confirm, and status endpoints.

**Comment by emmayank** [comment]
Hi @vishi24 , the JSONs for the above have been emailed to you. let me know if anything else is required.
