### ISSUE TITLE
Example JSON for ticket booking use case

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#22]
## Description

Currently, there are no sandbox collection / JSON examples for the hotel booking use case.
Study ticket booking websites for national parks / museums and based on that create the JSON examples for ticket booking use case.y

Please push the examples to https://github.com/beckn/beckn-sandbox/tree/main/src  under respective folder.

## Goals

- [x] Json examples for ticket booking use case

## Expected Outcome

JSON examples for the .ticket booking use case.

## Acceptance Criteria

- [x] JSON examples should contain search, select, init confirm, and status endpoints.

**Comment by emmayank** [comment]
Hi @vishi24 , the JSONs for the above have been emailed to you. let me know if anything else is required.
