### ISSUE TITLE
Postman collection for retail use case

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#25]
## Description

This postman collection will be for retail use case, purchasing pet food (Dog food).
Create postman collection for the retail booking use case details are as below
base_url - https://mit-ps-bap-client.becknprotocol.io
bap_id - mit-ps-bap.becknprotocol.io
bap_uri - https://mit-ps-bap.becknprotocol.io

Further details for registry , gateway , bpp are here - https://docs.google.com/spreadsheets/d/1X6RPNJH2eQrpjvHtZte9Jw6Zy0fIj7MNOcdlpr5iphE/edit#gid=2086670707

It should have, search, select, init confirm, cancel, and status endpoints.

Postman collection should be published under https://github.com/beckn/beckn-action-bot/artefacts/postman_collection

## Goals

- [ ] Postman collection pointing to BAP protocol server.

## Expected Outcome

Postman collection for retail use case that points to BAP protocol server.

## Acceptance Criteria

- [ ] All the listed endpoints must be there and the postman collection must be tested with BAP protocol server without any local services running.

**Comment by shreyvishal** [comment]
@vishi24 i haven't worked on this issue. I have worked on DSEP over the weekend and that too not for MIT-demo. So i should not be the owner of this ticket if its already `under review`.
cc: @faizmagic

**Comment by shreyvishal** [comment]
Assigning this to @zoyaashik as confirmed by @vishi24

**Comment by faizmagic** [comment]
current update
1. Retail catalogs are fully updated in the bpp
2. PR link attached to the ticket, which contains the postman collection to the retail
3. @zoyaashik to review the PR and ensure that postman collection for Retail is working as expected, by connecting to the new network for MIT Demo
4. verify if the base url in the postman collection is pointing to the MIT demo newtork

**Comment by zoyaashik** [comment]
Pointed the base url to MIT demo network and tested search, select,init,confirm,status endpoints.
The endpoints are working as expected.

**Comment by zoyaashik** [comment]
Mayur advised to take pull from main branch and re commit again.Hence done the same

**Comment by mayurvir** [comment]
Reviewed and merged, any issues discovered after this will be treated as separate bugs.
