### ISSUE TITLE
Postman collection for EV charging

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#26]
## Description

Create postman collection for the ev charging booking use case details are as below
base_url - https://mit-ps-bap-client.becknprotocol.io
bap_id - mit-ps-bap.becknprotocol.io
bap_uri - https://mit-ps-bap.becknprotocol.io

Further details for registry , gateway , bpp are here - https://docs.google.com/spreadsheets/d/1X6RPNJH2eQrpjvHtZte9Jw6Zy0fIj7MNOcdlpr5iphE/edit#gid=2086670707

It should have, search, select, init confirm, cancel, and status endpoints.

Postman collection should be published under https://github.com/beckn/beckn-action-bot/artefacts/postman_collection

## Goals

- [ ] Postman collection pointing to BAP protocol server.

## Expected Outcome

Postman collection for ev charging use case that points to BAP protocol server.

## Acceptance Criteria

- [ ] All the listed endpoints must be there and the postman collection must be tested with BAP protocol server without any local services running.

**Comment by shreyvishal** [comment]
@vishi24 i haven't worked on this issue. I have worked on DSEP over the weekend and that too not for MIT-demo. So i should not be the owner of this ticket if its already `under review`.
cc: @faizmagic

**Comment by shreyvishal** [comment]
Assigning this to @zoyaashik as confirmed by @vishi24

**Comment by faizmagic** [comment]
current update
1.  EV charging catalogs are fully updated in the bpp
2. PR link attached to the ticket, which contains the postman collection to the EV charging
3. @zoyaashik to review the PR and ensure that postman collection for EV charging is working as expected, by connecting to the new network for MIT Demo
4. verify if the base url in the postman collection is pointing to the MIT demo newtork

**Comment by zoyaashik** [comment]
Pointed the base url to MIT demo network and tested search, select,init,confirm,status endpoints.
The endpoints are working as expected.

**Comment by faizmagic** [comment]
@zoyaashik , can you provide details about the list of tables / columns in the strapi which are used for item.descriptor.name search

**Comment by zoyaashik** [comment]
the table sequence is as follows provider-> Item->sc_retail_product->price_brakeup

**Comment by mayurvir** [comment]
Reviewed and merged, any issues discovered after this will be treated as separate bugs.
