### ISSUE TITLE
Postman collection for DHP use case

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#27]
## Description

Create postman collection for the DHP use case details are as below
base_url - https://mit-ps-bap-client.becknprotocol.io
bap_id - mit-ps-bap.becknprotocol.io
bap_uri - https://mit-ps-bap.becknprotocol.io

Further details for registry , gateway , bpp are here - https://docs.google.com/spreadsheets/d/1X6RPNJH2eQrpjvHtZte9Jw6Zy0fIj7MNOcdlpr5iphE/edit#gid=2086670707

It should have, search, select, init confirm, cancel, and status endpoints.

Postman collection should be published under https://github.com/beckn/beckn-action-bot/artefacts/postman_collection

## Goals

- [ ] Postman collection pointing to BAP protocol server.

## Expected Outcome

Postman collection for DHP use case that points to BAP protocol server.

## Acceptance Criteria

- [ ] All the listed endpoints must be there and the postman collection must be tested with BAP protocol server without any local services running.

**Comment by faizmagic** [comment]
Current update
1. DHP catalogs fully updated in BPP
2. Search and select has been completed, the remaining endpoints needs to be tested.
3. Planned to complete the same by EOD
4. Raise a PR request

**Comment by zoyaashik** [comment]
Challenges faced on DHP
1. The response structure does not match sandbox response because we don not have below fields creds,language, skills,tags in agent Schema and Fulfillment-stops-range,days,,schedule in fulfilment schema. 
2.This has been highlighted during strap plugin development to @vishi24 
3. Only partial catalogue is uploaded in to Strap healthcare instance.

**Comment by zoyaashik** [comment]
As discussed with Faiz, Postman collection to be created with the information available in existing strapi tables. Pointed the DHP to MIT network and created PS collection for the same

**Comment by mayurvir** [comment]
Reviewed and merged. Any issues faced after this will be created as separate bugs.
