### ISSUE TITLE
Strapi plugin deployment and Data model update

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#58]
## Description

After the changes are made for the search functionality on Tag, keyword, and location is done. The enhanced Strapi plugin needs to be deployed on all instances.
Update the data model in all the instances.
**Validate the deployment using Postman collection.**

## Goals

- [ ] Strapi plugin deployment on all instances.
- [ ] Data model enhancement on all instances.

## Expected Outcome

Updated strapi plugin and data model on all instances of Strapi.

## Acceptance Criteria

- [ ] Updated data model on all instances.
- [ ] Update strapi plugin on all instances.
- [ ] Validate the deployment using postman collection.
- [ ] Validate that data model is reflected.

**Comment by shreyvishal** [comment]
Current Status: 

Deployed Updated Strapi Plugin on following isntance.
- MIT-bpp-tourism
- MIT-bpp-healthcare
- MIT-bpp-retail
- MIT-bpp-energy

@em-abee was working on `MIT-bpp-hotel` so haven't updated that instance.

Data Model Changes was done only in `MIT-bpp-tourism` . As for other instances didn't had app wasn't allowing to update
This needed to be done on other instances also.

cc: @mayurvir @faizmagic

**Comment by shreyvishal** [comment]
Adding extra 4 hours to the estimate as time is needed to figure out on how to grant permission to the user to update the data model. And re-deploy all instances again except `MIT-bpp-tourism`.

cc: @mayurvir @faizmagic @vishi24
