### ISSUE TITLE
Clone MIT Mumbai network to North Virginia

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-action-bot#66]
## Description

Make copy of all the 13 instances set up for the MIT demo in the North Virginia region.
The existing network in the Mumbai region will remain intact no changes should be made.
All the domains will have -nv at the end.

This migration will include database also for the Strapi.

Once the migration is done update the details in below sheet under north virginia infra sheet - https://docs.google.com/spreadsheets/d/1X6RPNJH2eQrpjvHtZte9Jw6Zy0fIj7MNOcdlpr5iphE/edit#gid=2086670707

Instances used by Mayur also needs to be migrated to the North Virginia region.
@mayurvir , please provide the details.

Detail of 3 instances
# Instances Overview

| Sr.No. | Instance Name       | Instance ID         | DNS                                                            |
|--------|---------------------|---------------------|----------------------------------------------------------------|
| 1      | MIT-bpp-hotel       | i-0dde43e2cd69a2f13 | [https://mit-bpp-hotel.becknprotocol.io/admin](https://mit-bpp-hotel.becknprotocol.io/admin) |
| 2      | MIT-bpp-tourism     | i-035ea722aaba3b693 | [https://mit-bpp-tourism.becknprotocol.io/admin](https://mit-bpp-tourism.becknprotocol.io/admin) |
| 3      | MIT-bpp-healthcare  | i-0326b93dea8a2d1ad | [https://mit-bpp-healthcare.becknprotocol.io/admin](https://mit-bpp-healthcare.becknprotocol.io/admin) |
| 4      | MIT-bpp-retail      | i-0f87e7d81ef3f365c | [https://mit-bpp-retail.becknprotocol.io/admin](https://mit-bpp-retail.becknprotocol.io/admin) |
| 5      | MIT-bpp-energy      | i-092c1d81213f68f83 | [https://mit-bpp-energy.becknprotocol.io/admin](https://mit-bpp-energy.becknprotocol.io/admin) |
| 6      | MIT-ps-hotel        | i-0b481d1a3e955d49e | [https://mit-ps-hotel.becknprotocol.io](https://mit-ps-hotel.becknprotocol.io) <br> [https://mit-ps-hotel-client.becknprotocol.io](https://mit-ps-hotel-client.becknprotocol.io) |
| 7      | MIT-ps-tourism      | i-05cc546c5853fe243 | [https://mit-ps-tourism.becknprotocol.io](https://mit-ps-tourism.becknprotocol.io) <br> [https://mit-ps-tourism-client.becknprotocol.io](https://mit-ps-tourism-client.becknprotocol.io) |
| 8      | MIT-ps-healthcare   | i-01a16ec8018074c9c | [https://mit-ps-healthcare.becknprotocol.io](https://mit-ps-healthcare.becknprotocol.io) <br> [https://mit-ps-healthcare-client.becknprotocol.io](https://mit-ps-healthcare-client.becknprotocol.io) |
| 9      | MIT-ps-retail       | i-02236bb06ebd59c63 | [https://mit-ps-retail.becknprotocol.io](https://mit-ps-retail.becknprotocol.io) <br> [https://mit-ps-retail-client.becknprotocol.io](https://mit-ps-retail-client.becknprotocol.io) |
| 10     | MIT-ps-energy       | i-0d32a362932a971d0 | [https://mit-ps-energy.becknprotocol.io](https://mit-ps-energy.becknprotocol.io) <br> [https://mit-ps-energy-client.becknprotocol.io](https://mit-ps-energy-client.becknprotocol.io) |
| 11     | MIT-gateway         | i-0958be2efa67542c6 | [https://mit-gateway.becknprotocol.io](https://mit-gateway.becknprotocol.io) |
| 12     | MIT-regitry         | i-0249fe186ceafcf8c | [https://registry-mit.becknprotocol.io](https://registry-mit.becknprotocol.io) |
| 13     | MIT-bap             | i-0290c72d45a6a4a68 | [https://mit-ps-bap.becknprotocol.io](https://mit-ps-bap.becknprotocol.io) <br> [https://mit-ps-bap-client.becknprotocol.io](https://mit-ps-bap-client.becknprotocol.io) |

## Goals

- [ ] Migration of MIT network and AI application setup in Mumbai region to North Virginia region.

## Expected Outcome

Working network in North Virginia region.

## Acceptance Criteria

- [ ] All 13 instances clone along with the DB
- [ ] AI application instance also cloned to North Virginia region
- [ ] The new network should work as existing network.

**Comment by prasad-takale-eminds** [comment]
We have created MIT instances in the AWS North Virginia region. 
The below tasks are done during this activity. 

1.  Create the AMI from existing EC2 instances for all 13 Application Instances and 1 DB instance. 
2. Copied AMI to AWS N.Virginia region
3. Fix the internet gateway issue on AWS N.Virginia region as internet is not allowed for the subnet.
4. Created 13 EC2 instances using copied AMI and deployed applications on those EC2 instances
5. Created DNS entry for all 13 EC2 instances on CloudFlare
6. Nginx configuration is done in all 13 EC2 instances along with a new SSL certificate for each DNS entry. 
7. Created DB instances using copied AMI
8. Made env file changes for Strapi EC2 instances for DB connection 
9. Redeployed the strapi application after DB changes. 

Below is the detail of migrated EC2 instances. 
Instance ID | Public IP | Name | ULRs
-- | -- | -- | --
i-026355c696a8bb016  | 35.173.42.27 | MIT-bpp-energy-nv | https://mit-bpp-energy-nv.becknprotocol.io/admin
i-0e1fc1c929d0e240d  | 44.192.13.145 | MIT-bpp-healthcare-nv | https://mit-bpp-healthcare-nv.becknprotocol.io/admin
i-00aecf79dbca5d408 | 18.210.27.238 | MIT-bpp-hotel-nv | https://mit-bpp-hotel-nv.becknprotocol.io/admin
i-0319677d8e84214b0 | 44.200.101.172 | MIT-bpp-retail-nv | https://mit-bpp-retail-nv.becknprotocol.io/admin
i-017c32a4c1e42fa39 | 44.221.90.33 | MIT-bpp-tourism-nv | https://mit-bpp-tourism-nv.becknprotocol.io/admin
i-0aab2e277b7714aa0 | 3.231.217.85 | MIT-ps-bap-nv | https://mit-ps-bap-nv.becknprotocol.io https://mit-ps-bap-client-nv.becknprotocol.io
i-03bfd63e791c83e79 | 3.235.40.36 | MIT-ps-energy-nv | https://mit-ps-energy-nv.becknprotocol.iohttps://mit-ps-energy-client-nv.becknprotocol.io
i-04b838a92f17b465d | 44.197.228.249 | MIT-ps-healthcare-nv | https://mit-ps-healthcare-nv.becknprotocol.iohttps://mit-ps-healthcare-client-nv.becknprotocol.io
i-09b7397b225d4cf15 | 3.230.159.39 | MIT-ps-hotel-nv | https://mit-ps-hotel-nv.becknprotocol.iohttps://mit-ps-hotel-client-nv.becknprotocol.io
i-0ac103135013858ea | 44.211.24.190 | MIT-ps-retail-nv | https://mit-ps-retail-nv.becknprotocol.iohttps://mit-ps-retail-client-nv.becknprotocol.io
i-07c7b5aa7c521c61f | 34.204.202.196 | MIT-ps-tourism-nv | https://mit-ps-tourism-nv.becknprotocol.iohttps://mit-ps-tourism-client-nv.becknprotocol.io
i-070bd9a82d8266f30 | 44.213.60.22 | MIT-regitry-nv | https://registry-mit-nv.becknprotocol.io
i-0dbb0335513b1fd40 | 44.201.95.117 | MIT-gateway-nv | https://mit-gateway-nv.becknprotocol.io
