### ISSUE TITLE
AI bot UAT

### ISSUE THREAD

**Issue by meenakshi2468** [beckn/beckn-action-bot#78]
## Description

Viraj to conduct end-to-end testing of the AI bot to verify the functionality of all intended flows. 

This includes testing various user interactions to ensure the bot responds accurately and appropriately in different scenarios.
Screenshots or recordings to be provided as proof of completion, showcasing successful navigation through the bot and validation of expected outcomes across all tested flows.

## Acceptance Criteria

Comprehensive Testing: Viraj must test all intended user flows within the AI bot, covering various scenarios and interactions to ensure thorough validation of functionality.

Accuracy: The bot's responses should be accurate and relevant to user queries, reflecting a deep understanding of the provided information and context.

Consistency: The bot's behavior should remain consistent across different flows and interactions, maintaining uniformity in responses and user experience.

Validation of Intended Flows: Viraj should verify that all intended flows, features, and functionalities specified for the bot are working as expected without any errors or deviations.

Documentation of Testing: Viraj must document the testing process, including any issues encountered, steps taken to reproduce them, and resolutions implemented, ensuring comprehensive record-keeping for future reference.

Proof of Completion: Screenshots or recordings should be provided as evidence of the testing process, demonstrating successful navigation through the bot and validation of expected outcomes across all tested flows.

**Comment by mayurvir** [comment]
A fresh issue needs to be created for this based on the new agent structure.
